# This file is automatically generated. Do not edit.

PXEngine.licenseKey('GKTIM-1HG85-71O18-4EUJ3-SE0CF-VN7SS-2N8TE-3303R-BL2OK-A767N-V5G87-K8UE9-R1IGK-O0MQ5-J1HTR-1C', forUser:'neil@plasticwater.com')

def style(str)
  PXStylesheet.styleSheetFromSource(str, withOrigin:0)
  PXStylesheet.applyStylesheets
end
