# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('df1d9a7ea54333ddd6e72e9dbc9c566d_Njg5OTIyMDEyLTAzLTA3IDE0OjI3OjAzLjM5ODk0OA')
  end)
end
